export default [
  "Not all answers come at once.",
  "Silence sometimes speaks louder.",
  "Your pace is your choice.",
  "Not everything needs to be explained.",
  "Sometimes a pause is a movement.",
  "You don’t have to react.",
  "Simple decisions are powerful too.",
  "Not every moment requires action.",
  "Doubt is part of thinking.",
  "Not everything that seems important is.",
  "Decisions become clear after a choice.",
  "You can change direction at any time.",
  "Expectation changes perception.",
  "Sometimes it’s worth letting go of control.",
  "Thoughts don’t always need an answer.",
  "What you feel is a signal.",
  "Not all conversations have a sequel.",
  "Boundaries begin with a decision.",
  "Your reaction shapes the outcome.",
  "Sometimes it’s better to observe.",
  "You don’t have to be comfortable.",
  "Decisions can be quiet.",
  "Not everything needs to be fixed.",
  "Clarity is peace.",
  "You can say “no” without explanation.",
  "Sometimes the answer is no answer.",
  "Small choices create big direction.",
  "Not every path requires speed.",
  "Your state is more important than expectations.",
  "Sometimes just being there is enough."
]