export default [
  "If you don’t know what to do, clarify.",
  "They didn’t answer right away — it’s not always about you.",
  "A short pause is better than an impulsive reaction.",
  "If something is annoying — name it to yourself.",
  "Not all conversations need to be continued.",
  "Doubt is a signal to think, not to run away.",
  "A simple question often solves the difficulty.",
  "Silence is also an answer option.",
  "You can disagree and not conflict.",
  "Sometimes it’s better to change the subject than to argue.",
  "Not all thoughts should be voiced at once.",
  "If something is unclear — that’s okay.",
  "Clarity saves time and nerves.",
  "Not every reaction requires an answer.",
  "You don’t have to explain everything.",
  "Intonation is more important than words.",
  "Slower is sometimes smarter.",
  "When in doubt, ask.",
  "Postponing is also a decision.",
  "Not everything needs to be fixed.",
  "Your reaction is your choice.",
  "Sometimes it’s better to leave than to stay.",
  "A direct answer saves time.",
  "Not all situations require emotions.",
  "Listening is also an action.",
  "You can change your mind.",
  "Not everything needs to be controlled.",
  "Better short and clear than long and confusing.",
  "If something is not yours, let it go.",
  "The reaction now affects the outcome later."
]